### ISSUE TITLE
Input term error in console output

### ISSUE THREAD

**Issue by coldfusioneer** [WGLab/EHR-Phenolyzer#8]
I found this input term error message in the console output several times when I ran the EHR-Phenolyzer on my clinical notes. However, not all the notes produced this type of 'error'. They ran fine. I checked my notes and they didn't have the underscores as suggested in the error below. All the output files were produced at the end of the run. Any idea what's causing this?

Here's an example from one note:
ERROR: The input term -----appendicular_hypotonia------ has no corresponding names in the disease database, please check your spelling!!!
ERROR: The input term -----cephalohematoma------ has no corresponding names in the disease database, please check your spelling!!!
ERROR: The input term -----vaginal_hydrocele------ has no results!!!

Output from the HPO file:
HP:0000078	Abnormality of the genital system
HP:0009800	Maternal diabetes
HP:0200128	Biventricular hypertrophy
HP:0001252	Muscular hypotonia
HP:0001290	Generalized hypotonia
HP:0012389	Appendicular hypotonia
HP:0001321	Cerebellar hypoplasia
HP:0001320	Cerebellar vermis hypoplasia
HP:0000034	Hydrocele testis
HP:0100673	Vaginal hydrocele
HP:0012541	Cephalohematoma
HP:0006956	Dilation of lateral ventricles
HP:0006817	Aplasia/Hypoplasia of the cerebellar vermis

UPDATE: Found the text for the error message generated by disease_annotation.pl (Phenolyzer) line 299. The condition for the error is if(@diseases==0). I don't know Perl scripts that well to assess the code. Sounds like it couldn't find the disease from the HPO terms. Thoughts?

**Comment by kaichop** [comment]
I cannot quite understand your question.

The "_" is added automatically to connect several words together into a
phrase and then assess if they are found in pre-compiled databases in
Phenolyzer. In this case, these three words are not found in the
pre-compiled database.

**Comment by coldfusioneer** [comment]
I guess I was wondering if it was an exception error and the program was not able to process the code correctly. The 'error' message had suggested that there was a spelling error but I couldn't find them in my clinical notes. I was not confident initially if the program had ran exactly as intended. It sounds like from your explanation that the 'error' was because it was a mismatched term (e..g. disease name not found public databases - I did a brief check using the term cephalohematoma in HPRD and the query did not return any results). 

Follow up questions:
- What are these pre-compiled databases? OMIM, HPRD?
- Are these databases pre-compiled during run time? Are they frequently updated to reflect the latest update from public databases such as HPRD, HTRIdb?

**Comment by kaichop** [comment]
Without providing any information such as command line argument and the
procedure, I truly have little idea what you are referring to. I do not
even know whether you are referring to a web server or a command line
program or anything else, since we have developed a few different tools for
this purpose. I do not even know what you mean by "output" "input" or
"output from HPO file". I am clueless what you are doing, except that I can
see that the error message is thrown by Phenolyzer itself.

The database I was referring to are part of Phenolyzer, which is a
component of EHR-Phenolyzer. You need to read the original paper on
Phenolyzer if you want to learn more about it. There are many ways to run
EHR-Phenolyzer as well.

If this is too complicated for you, I suggest that you simply use
phen2gene.wglab.org, then all technical details are hidden and you get
results directly.

**Comment by coldfusioneer** [comment]
I apologize if I wasn't being clear. I'm happy to provide any information that you need to help us troubleshoot/explain this phenomenon. As my title suggest, I ran the command line in the command console. So, it's not the web-based program as you had suggested earlier. Since this is EHR-Phenolyzer github page, I thought it's appropriate that I ask questions about EHR-Phenolyzer over here, although I must admit Phenolyzer is part of the program too.

python ehr_phenolyzer.py -i 12345.txt -p thisisatest -n "metamap" 

'Input' was referred to the text that appeared here 'ERROR: The input term ....'
I was referring the 'output of the HPO' to the HPO.txt file that EHR-phenolyzer generates after running the program. I hope this is clear enough for you.

Thanks for pointing out the paper. I can see now that these pre-compiled databases that you spoke about was referring to data sources such as OMIM, Orpanet, ClinVar, Gene Reviews and GWAS catalog. Is this the current list (has it expanded?) and when the EHR-Phenolyzer program does the pre-compilation, is it getting the latest data from these sources?

**Comment by kaichop** [comment]
if you used "git clone https://github.com/WGLab/phenolyzer" to install
Phenolyzer, then you should have the latest version. This latest version
includes one additional database (JAX HPO annotation) to be used in the
gene scoring procedure.

So basically phenolyzer can accept HPO ID as input now, I think you can
just use "HP:0000078 HP:0009800" etc to directly run phenolyzer and analyze
the clinical texts instead of the phrases (maybe this solves the issue that
these phrases are not found).

**Comment by coldfusioneer** [comment]
Thank you for your feedback and suggestions. Based on these conversations, I think we can safely agree there is nothing wrong with the clinical notes or the phrases that appeared in the notes. I tested the phenotypes (by using the HPO id) on Phenolyzer and Phen2Gene, and all of it returned with no results. 

HP:0012389 Appendicular hypotonia
HP:0100673 Vaginal hydrocele
HP:0012541 Cephalohematoma

This seems to suggest that there aren't any genes associated with these phenotypes at the moment.

**Comment by kaichop** [comment]
If you used the latest version of Phenolyzer (through git clone), then yes
there are no genes associated with these phenotypes. Thank you.
